### ISSUE TITLE
Generic Torznab scraper

### ISSUE THREAD

**Issue by b4154** [Gabisonfire/torrentio-scraper-sh#11]
This would allow us to use Prowlarr and unlock a wide amount of indexers to use. Also would deal with Flaresolverr.

**Comment by Gabisonfire** [comment]
Prowlarr works like Jackett and is more of an on-demand search indexer while Torrentio works by scraping. I'll still see what I can do, if there's a possibility to have both and eventually try to merge this feature upstream.

**Comment by Pukabyte** [comment]
There's already a way to do this. We've written an indexer to import into Prowlarr.
https://github.com/Pukabyte/Prowlarr-Indexers/blob/main/Custom/torrentio.yml
This file needs to be put inside of the prowlarr directory in for example /opt/prowlarr/Definitions/Custom/torrentio.yml

Then change the url to your self hosted torrentio

**Comment by b4154** [comment]
> There's already a way to do this. We've written an indexer to import into Prowlarr. https://github.com/Pukabyte/Prowlarr-Indexers/blob/main/Custom/torrentio.yml This file needs to be put inside of the prowlarr directory in for example /opt/prowlarr/Definitions/Custom/torrentio.yml
> 
> Then change the url to your self hosted torrentio.
> 
> It works off the bat with the main torrentio, but when using selfhosted, it needs to do a full scrape before it will work

Thanks, this is neat! Will definitely use this. 

I was mainly referring to using Torznab as a way to interface with indexers for scraping, but after looking into it, Jackett and Prowlarr both don't really have pagination implemented on most of the yaml definitions. It would only show the most recent torrents so that wouldn't really work for scraping entire indexers :/

**Comment by Gabisonfire** [comment]
See https://github.com/Gabisonfire/torrentio-scraper-sh/issues/7#issuecomment-1913775038
