### ISSUE TITLE
Addon Cannot find any torrent

### ISSUE THREAD

**Issue by Mizaro** [Gabisonfire/torrentio-scraper-sh#13]
When trying to see Scrubs I don't see anything loading. it is immediately shows "No addons"

**Comment by rijoymanghat** [comment]
Getting same issues

**Comment by epthewizard** [comment]
same

**Comment by borisnet** [comment]
I got some contents with RD links but the majority has nothing. So it is not like it is totally broken but it does not seem to pull much

**Comment by Gabisonfire** [comment]
How long did you wait for scraping? Had to go a good 24 hours to get a lot of results. Also, please poat some scraping logs.

**Comment by borisnet** [comment]
@Gabisonfire  - I have not waited much to be fair however I have seen an immediate difference by adding the following: https://github.com/Gabisonfire/torrentio-scraper-sh/pull/10

Can you expand on why there is a difference?

**Comment by Gabisonfire** [comment]
If you check the log, you'll see that one service had issues communicating with the database. `depends` tells docker to wait for other services to be up and running

**Comment by Gabisonfire** [comment]
If you still have issues, please resubmit an issue including logs for all containers.
