### ISSUE TITLE
ERR_OPENING_MEDIA

### ISSUE THREAD

**Issue by Nalith** [Gabisonfire/torrentio-scraper-sh#16]
When trying to install the addon (After configuring it) I get the following error:

![image](https://github.com/Gabisonfire/torrentio-scraper-sh/assets/4245203/4055e1ca-5148-400f-8af5-b7c12f442970)

**Comment by Gabisonfire** [comment]
https://github.com/Gabisonfire/torrentio-scraper-sh/issues/4
