### ISSUE TITLE
scraping errors

### ISSUE THREAD

**Issue by ash32152** [Gabisonfire/torrentio-scraper-sh#27]
hey :)

thanks for all the work on this, I was wondering if anyone has as many issues scraping as I do or any ways to circumvent it. I realize that most the issues will be upstream with bot protection etc. but I'm struggling to seed my initial db due to the errors so makes it feel quite pointless at the moment.

YTS - full scrape - seems to get to page 200 odd and then fail;

Scrapping YTS page 149

Failed YTS scrapping for [149] due:  Error: Failed browse request

    at browse (/home/node/app/scrapers/yts/yts_api.js:35:27)

    at /home/node/app/scrapers/yts/yts_api.js:42:23
    
eztv - fails first top 10 scrape;

[Thu Feb 01 2024 19:31:43 GMT+0000] starting EZTV scrape...

Scrapping EZTV page 1

Failed EZTV scrapping for [1] due:  TypeError: Cannot read properties of undefined (reading 'replace')

    at parseTorrent (/home/node/app/scrapers/eztv/eztv_api.js:79:36)

    at /home/node/app/scrapers/eztv/eztv_api.js:73:42

    at Array.map (<anonymous>)

    at parseResults (/home/node/app/scrapers/eztv/eztv_api.js:73:27)

    at /home/node/app/scrapers/eztv/eztv_api.js:52:24

[Thu Feb 01 2024 19:31:50 GMT+0000] finished EZTV scrape

1337x - a lot better since the latest commit (although occasionally keep getting a 429 - too many requests) to pass the cookie using the one request, although it now only seems to attempt movies/tv/anime/docs top 10 and then 'Finished scraping 1337x' and that's where the container hangs.

I couldn't seem to get the schedule working, I dropped the ENABLE_SCHEDULING var in and it complained about trackers having 0 seeders and some node errors.

I'm scraping over a VPN which I'm sure will add to the problem as the amount of requests coming from that IP is going to be more heavily challenged.

Each time they fail and get to the end loop, I have to kick the container and start round again. Was wondering if I'm missing something here as I've seen multiple threads about saying peoples have been scraping for 6+ hours etc.

Any advice would be appreciated, thanks!

**Comment by funkypenguin** [comment]
I just [disabled the updating of seeders in the schedule](https://github.com/geek-cookbook/torrentio.elfhosted.com/commit/b57217c5db50a7760ec0c3ad74ef379b3e47831b) for now, since I don't know what it does, and clearly it's not doing it nicely anyway ;)

**Comment by ash32152** [comment]
Ah thank you, I'll give that a go! :)

**Comment by trulow** [comment]
@Gabisonfire We can probably close this issue as it no longer applies due to the new updates.
