### ISSUE TITLE
ERR_OPENING MEDIA

### ISSUE THREAD

**Issue by Neowam** [Gabisonfire/torrentio-scraper-sh#4]
When i try to install i am getting this error on my Windows Stremio:

![image](https://github.com/Gabisonfire/torrentio-scraper-sh/assets/94406673/1f714c35-7cdf-45b4-9d61-bc9c6486f0fa)

All is running fine at :7000 for so far I can see

**Comment by Neowam** [comment]
I found something
- while using 127.0.0.1:7000, i can perfectly add the addon
- while using my IP of my home device 192.168.100.x:7000 I am getting this error above

**Comment by kratoz29** [comment]
I am facing the same error maybe it needs to run with a https link? I'm just saying that as I have seen some user shared his, which it is using SSL certificates and such.

**Comment by su-kkasberg** [comment]
> I am facing the same error maybe it needs to run with a https link? I'm just saying that as I have seen some user shared his, which it is using SSL certificates and such.
> 
> EDIT: Yeah I was able to add it to my Stremio using a reverse proxy with a Let's encrypt certificate, still it was not able to scrap anything... I'm stuck at that.

I was able to get things working after setting up reverse proxy with lets encrypt on port 443.   The scrapper is working till it gets to 1337, where it throws errors.   I am getting options to stream for the content that succeeded.

**Comment by Gabisonfire** [comment]
Sorry for some reason I did not get the notifications for these issues. Yes, Stremio will allow 127.0.0.1 to run in plain http but anywhere else needs to be with a valid certificate. In this case, the easiest is to have a reverse proxy with Let's Encrypt.

**Comment by Neowam** [comment]
I downloaded Nginx Proxy Manager and created a proxy host, unfortunately i am not be able to redirect 443 > 7000. 
I am getting a 502 Bad Gateway.
I am sure I did the right thing, cause when redirecting to 81, i am getting successfully login screen of Nginx Proxy Manager

Any idea?

**Comment by Nalith** [comment]
Thank you for the prompt response, that worked like a charm!
