### ISSUE TITLE
Possible to create docker image for CLI?

### ISSUE THREAD

**Issue by JRDevo** [Gabisonfire/torrentio-scraper-sh#6]
Fairly new to docker (at least compose) I normally look around for docker cli's, is it possible to create an image from this?

Any help/guidance appreciated.

**Comment by Sku1ly** [comment]
Are you using Home Assistant?
I installed the portainer add on then followed this guide - https://thenewstack.io/deploy-a-container-stack-in-portainer-from-a-github-repository/#:~:text=First%2C%20add%20a%20Docker%20compose,full%20stack%20container%20in%20Portainer.

**Comment by timknowlden** [comment]
Im trying to work out how to install on unraid

**Comment by Gabisonfire** [comment]
Do you mean individual commands? Your'e better off learning how to use compose. It's fairly simple and will deploy everything you need at once.

**Comment by timknowlden** [comment]
Yeah individual docker containers I'm used to, especially with unraid. Very familiar and easy to implement. Never used compose, but I'm trying

**Comment by Gabisonfire** [comment]
Found this: https://8gwifi.org/dc2.jsp

**Comment by timknowlden** [comment]
> Found this: https://8gwifi.org/dc2.jsp

That could be helpful, I'll try shortly
