### ISSUE TITLE
Possible to share DB?

### ISSUE THREAD

**Issue by matukaa** [Gabisonfire/torrentio-scraper-sh#7]
Heyo,

Fairly new to docker, managed to get it set up and host it using ngrok, but the main pain point is the scraping, which will take weeks probably to finish in the current tempo (just YTS alone, and there are more).

Is there a way to import a db from someone who already finished scraping? If so, are there any dumps available?
I saw that the readme for scraper contains initial dumps for TPB and Kickass, but the mega links point to empty folders

Cheers

**Comment by Neowam** [comment]
Is it not possible to run multiple scrapers instead of one?

**Comment by Gabisonfire** [comment]
I'm looking into some kind of solution to this, but the issie with sharing dbs is that it's subject to dmca claims, just like trackers.

**Comment by su-kkasberg** [comment]
I was able to get one of the load files from internet archive, but I am not sure how to import it.   How do I import a bulk file?

**Comment by davidjameshowell** [comment]
> I was able to get one of the load files from internet archive, but I am not sure how to import it. How do I import a bulk file?

You would need to write a new scraper that reads the dump that you found and proceed to run each time through. You can look at the existing scrapers to examine how they process each individual torrent and model after that.

**Comment by Gabisonfire** [comment]
Thanks for your input again @davidjameshowell , always helpful as usual. 
After taking some time to look at sharing the DB, it's not something that is easily doable. 
I'm not going to spend time working into the app's code for a few reasons:

- It makes it harder to keep up with the upstream
- I hate JS
- I have plans for a completely seperate add on
- The original dev shows no interest in sharing his scrapers

I will support this fork when it comes to making the dependencies work, but I don't see this as a long term project.
