### ISSUE TITLE
Error occured while adding addon

### ISSUE THREAD

**Issue by timknowlden** [Gabisonfire/torrentio-scraper-sh#8]
Webpage works to select sources and qualities etc.. when going to add the addon I get the error:

Error occured while adding addon.

Do you think stremio is wise to this now?

**Comment by su-kkasberg** [comment]
It needs to be behind tls (https) is what I found. It also have to be accessible by stremio servers (outside of your network)

**Comment by timknowlden** [comment]
> It needs to be behind tls (https) is what I found. It also have to be accessible by stremio servers (outside of your network)

Yes missed a bit that stated about being reverse proxied, it is now... but i get no results

<img width="410" alt="image" src="https://github.com/Gabisonfire/torrentio-scraper-sh/assets/73787006/bfad35b9-80dc-4d25-8b35-e2e3b7644fc4">

**Comment by su-kkasberg** [comment]
Look at your scraper logs and search for something that was added. It takes a while for the scraper to load the db with links. 

I have a lot of movies loaded, but no shows yet because it’s still scrapping.

**Comment by timknowlden** [comment]
> Look at your scraper logs and search for something that was added. It takes a while for the scraper to load the db with links.
> 
> I have a lot of movies loaded, but no shows yet because it’s still scrapping.

Ive got this error in torrentio container, cannot open log on scraper, it closes itself.

```text  error  warn  system  array  login  

(node:1) Warning: Using insecure HTTP parsing
(Use `node --trace-warnings ...` to show where the warning was created)
Failed request tt26745417:1:1: SequelizeConnectionRefusedError: connect ECONNREFUSED 172.21.0.3:54321
Failed request tt1517268: SequelizeConnectionRefusedError: connect ECONNREFUSED 172.21.0.3:54321
Retrieved best trackers:  [
  'http://tracker.opentrackr.org:1337/announce',
  'udp://tracker.auctor.tv:6969/announce',
  'udp://opentracker.i2p.rocks:6969/announce',
  'https://opentracker.i2p.rocks:443/announce',
  'udp://open.demonii.com:1337/announce',
  'http://tracker.openbittorrent.com:80/announce',
  'udp://open.stealth.si:80/announce',
  'udp://tracker.torrent.eu.org:451/announce',
  'udp://exodus.desync.com:6969/announce',
  'udp://tracker.moeking.me:6969/announce',
  'udp://explodie.org:6969/announce',
  'https://tracker.tamersunion.org:443/announce',
  'udp://uploads.gamecoast.net:6969/announce',
  'udp://tracker1.bt.moack.co.kr:80/announce',
  'udp://tracker.tiny-vps.com:6969/announce',
  'udp://tracker.theoks.net:6969/announce',
  'udp://tracker.skyts.net:6969/announce',
  'udp://tracker-udp.gbitt.info:80/announce',
  'udp://retracker01-msk-virt.corbina.net:80/announce',
  'udp://open.u-p.pw:6969/announce'
]
Started addon at: http://localhost:7000
MongoServerSelectionError: getaddrinfo ENOTFOUND mongodb
    at Timeout._onTimeout (/home/node/app/node_modules/mongodb/lib/core/sdam/topology.js:438:30)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) { 'mongodb:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
Current stats:  { RECEIVED: 0, QUEUED: 0, RUNNING: 0, EXECUTING: 1 }
Incoming catalog torrentio-realdebrid request with skip=0
MongoServerSelectionError: getaddrinfo ENOTFOUND mongodb
    at Timeout._onTimeout (/home/node/app/node_modules/mongodb/lib/core/sdam/topology.js:438:30)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) { 'mongodb:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
Current stats:  { RECEIVED: 0, QUEUED: 0, RUNNING: 0, EXECUTING: 1 }

**Comment by su-kkasberg** [comment]
so you can add the addon in stremio, right?   If you can, and then you are getting no results, it looks to me like its your scaper hasn't loaded anything into the DB.   I would look at the DB or scraper container for errors.

**Comment by timknowlden** [comment]
> so you can add the addon in stremio, right? If you can, and then you are getting no results, it looks to me like its your scaper hasn't loaded anything into the DB. I would look at the DB or scraper container for errors.

Yes I can add the addon in stremio. I cannot open the logs for the other containers, only the stremio one.. so suggests theres an issue with the config.

here is my compose:

```version: '3.9'
name: torrentio-self-host

services:

  mongodb:
    restart: unless-stopped
    image: docker.io/bitnami/mongodb:7.0
    ports:
      - "27017:27017"
    volumes:
      - /mnt/user/appdata/torrentio/mongo-data:/bitnami/mongodb
    labels:
      - "io.portainer.stack.icon=mongodb"
      - "io.portainer.stack.color=#35bc4b"  # Set a color for the icon if your UI supports it
  
  scraper:
    build: /mnt/user/appdata/torrentio/scraper
    restart: unless-stopped
    environment:
      - PORT=7001
      - MONGODB_URI=mongodb://mongodb:27017/torrentio
      - DATABASE_URI=postgres://postgres@postgres:54321/torrentio
      - ENABLE_SYNC=true
    labels:
      - "io.portainer.stack.icon=scraper"
  
  torrentio:
    build: /mnt/user/appdata/torrentio/addon
    restart: unless-stopped
    ports:
      - "7000:7000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/torrentio
      - DATABASE_URI=postgres://postgres@postgres:54321/torrentio
      - ENABLE_SYNC=true
    labels:
      - "io.portainer.stack.icon=torrentio"
  
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "54321:5432"  # Change the port to 54321
    volumes:
      - /mnt/user/appdata/torrentio/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_DB=torrentio
    labels:
      - "io.portainer.stack.icon=postgres"

volumes:
  mongo-data:
  postgres-data:
```

**Comment by Gabisonfire** [comment]
Your mongodb is not running properly, please check the logs.

@su-kkasberg it does require a validd ssl certificate but it does not have to be publicly available.

**Comment by timknowlden** [comment]
> Your mongodb is not running properly, please check the logs.
> 
> @su-kkasberg it does require a validd ssl certificate but it does not have to be publicly available.

Yes I see that's not running in the lot, compose is copied from your repo though. Im clearly over looking something.

**Comment by Gabisonfire** [comment]
Try `docker ps -a` and then `docker logs container_name` on the mongodb container and post your logs here.

**Comment by timknowlden** [comment]
> Try `docker ps -a` and then `docker logs container_name` on the mongodb container and post your logs here.

The second I open console on the mongodb container it closes the window. I can't get to the point of typing anything in at all. 

I'll see if I can create an external mongodb container and use that, I've already got another postgres container running which is why I've mapped port to 54321 on the compose

**Comment by timknowlden** [comment]
> > Try `docker ps -a` and then `docker logs container_name` on the mongodb container and post your logs here.
> 
> The second I open console on the mongodb container it closes the window. I can't get to the point of typing anything in at all.
> 
> I'll see if I can create an external mongodb container and use that, I've already got another postgres container running which is why I've mapped port to 54321 on the compose

Because I haven't yet worked out how to not use host ip.

**Comment by Gabisonfire** [comment]
What do you mean by "the console on the mongodb container"? If you are using portainer or some kind of ui, you need to run these commands directly on the host, without mondogb container logs, there's nothing that can be done.

**Comment by timknowlden** [comment]
> What do you mean by "the console on the mongodb container"? If you are using portainer or some kind of ui, you need to run these commands directly on the host, without mondogb container logs, there's nothing that can be done.

This is what i mean, inside unraid you can right click on a container and go into its console, stop, start, view logs

<img width="533" alt="image" src="https://github.com/Gabisonfire/torrentio-scraper-sh/assets/73787006/f7e6863c-73ef-4d62-8659-7098585b6bd0">

**Comment by grapeslush** [comment]
He's probably seeing this. I'm seeing the same. Think it might be related to architecture but i'm on x86, not ARM.

`exec /opt/bitnami/scripts/mongodb/entrypoint.sh: exec format error
exec /opt/bitnami/scripts/mongodb/entrypoint.sh: exec format error`

**Comment by Gabisonfire** [comment]
Yes, this is arch related. If you are running this on a VM, make sure the cpu supports avx. In proxmox, this can be fixed by setting the cpu to "host".

**Comment by grapeslush** [comment]
Running on bare metal host. It's a relatively new CPU, but I'll check for AVX support.

**Comment by grapeslush** [comment]
Swapped to mongodb/mongodb-community-server:latest and had no problems. Turns out the machine I was using is ARM lol. Was using a different machine than I thought I was. Problems of having too many host.
